config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users
  resources :items
  resources :orders
  resources :carts
  resources :order_items, only: %i[create destroy]
  resources :orders, only: %i[create show]
  post 'order_items/:id/add' => 'order_items#add_quantity', as: 'order_items_add'
  post 'order_items/:id/reduce' => 'order_items#reduce_quantity', as: 'order_items_reduce'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :users
  end

  get '/search' => 'items#filter'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  belongs_to :user

  validates :user, uniqueness: true

  def import_order(order)
    order.order_items.each do |order_item|
      OrderItem.create!(cart: self, item: order_item.item, quantity: order_item.quantity)
    end
  end

  def self.empty_for(user)
    user.cart.destroy
    cart = Cart.new(user: user)
    cart.save
  end

  def total_price
    sum = 0
    order_items.each { |order_item| sum += order_item.total_price }
    sum
  end

  def total_quantity
    sum = 0
    order_items.each { |order_item| sum += order_item.quantity }
    sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, :my_cart?

  def show
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    @cart = Cart.new
    @cart.user = current_user
    @cart.save
    redirect_to cart_path(@cart)
  end

  private

  def my_cart?
    return if current_user.cart == Cart.find(params[:id])

    redirect_back fallback_location: root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_item-cart.html.erb
<div class="item-cart-wrapper">
  <div class="cart-card-wrapper flex justify-between rarity-cart-<%=order_item.item.rarity%>">
    <div class="item-card cart-card ">  
      <img src="<%=order_item.item.image_url%>" alt="">
    </div>
    <div class="item-card-content flex">
      <div class="item-card-content-header flex justify-between">
        <p class="p-content cart-page"><%=order_item.item.title%></p>
        <p class="p-content cart-page"><%='%.02f' % (order_item.total_price)%> €</p>
        <%= button_to order_item_path(order_item), method: 'delete', class:'bin-icon' do %>
          <i class="fas fa-times fa-2x"></i>
        <% end %>
        
      </div>
      <div class="cart-item-quantity flex ">
        <%= button_to "-", order_items_reduce_path(order_item), class: "minus" %>    
        <p class="p-content "><%=order_item.quantity%></p>
        <%= button_to "+", order_items_add_path(order_item), class: "plus" %> 
      </div>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<%= render 'layouts/hero-little' %>
<main class="main-responsive container mx-auto mt-20 px-5 grid grid-cols-10">
  <% if @cart.order_items.present? %>
    <div class="item-section col-span-6">
      <% @cart.order_items.each do |order_item| %>
        <%= render partial: "item-cart", locals:{order_item: order_item} %>
      <% end %>
    </div>
    <div class="summary-section col-span-4">
      <h1 class="sub-title">Summary :</h1>
      <div class="summary-section-header">
        <p class="p-content">
          <%= @cart.total_quantity %> products
        </p>
        <%= button_to  cart_path(@cart), method: 'delete' do %>
          <i class="fas fa-trash fa-2xl"></i>
        <% end %>
      </div>
        <div class="summary-section-footer">
        <p class="p-content">
          Total : 
        </p>
        <p class="p-content">
          <%= '%.02f' % @cart.total_price %>€
        </p>
        <%= button_to "Payer", checkout_create_path(total: @cart.total_price), class: "btn btn-primary", remote: true, data: { turbo: false } %>
      </div>
    </div>
  <% else %>
      <div class="sub-title col-span-6">Your cart is empty, go fill it !</div>
  <% end %>
</main>