config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users
  resources :items
  resources :orders
  resources :carts
  resources :order_items, only: %i[create destroy]
  resources :orders, only: %i[create show]
  post 'order_items/:id/add' => 'order_items#add_quantity', as: 'order_items_add'
  post 'order_items/:id/reduce' => 'order_items#reduce_quantity', as: 'order_items_reduce'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :users
  end

  get '/search' => 'items#filter'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :carts, through: :order_items
  belongs_to :category

  validates :title, presence: true,
                    uniqueness: true,
                    length: { in: 3..30 }
  # format: { with: %r{\A[\w -/]\z} }

  validates :description, presence: true,
                          length: { in: 5..500 }

  validates :price, presence: true,
                    numericality: { greater_than: 0 }

  validates :rarity, presence: true,
                     numericality: { in: 0..4 }

  validates :image_url, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show 
    @item = Item.find(params[:id])
  end
  def filter
    @items = Item.all
    @items_filtered = Item.where(rarity: params[:search])
    @items_filtered_by_title = Item.where(title: params[:search])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_card.html.erb
<div class="card">
  <img class="card-rarity" src="<%=image_path("rarity-#{item.rarity}.png")%>">
  <a href="<%=item_path(item)%>" data-turbo="false">
    <div class="small-card item-card card_full max-w-sm overflow-hidden shadow-lg rarity-<%=item.rarity%>">
      <div class="card-texture">
        <img class="w-full " src="https://i.imgur.com/vbCJQJe.png" alt="texture">
      </div>
      <div class="card-background">
        <img class="w-full " src="<%=item.image_url%>" alt="">
      </div>
      <div class="card-content">
        <div class="card-title"><%= item.title %></div>
      </a>
        <div class="card-footer">
          <div class="card-price "><%= item.price %> €</div>
            <% if user_signed_in? %>
              <%= button_to "Add to cart", order_items_path(item_id: item.id), class: "card-add-btn" %>
            <% else %>
              <%= button_to "Add to cart", new_user_session_path, class: "card-add-btn"%>
            <% end %>
        </div>
      </div>
    </div>
</div>

app/views/items/filter.html.erb
<%= render 'layouts/hero-banner' %>
<main class="container mx-auto mt-28 px-5">
  <div class="grid  xl:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 justify-center">
    <% @items_filtered_by_title.each do |item| %>
      <%= render partial: 'card', locals:{item: item}  %>
    <% end %>
    <% @items_filtered.each do |item| %>
      <%= render partial: 'card', locals:{item: item}  %>
    <% end %>
  </div>
  </main>

app/views/items/index.html.erb
<%= render 'layouts/hero-banner' %>
<main class="item-index-page container mx-auto mt-28 px-5">
  <div class="grid  xl:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 justify-center  ">
    <% @items.each do |item| %>
      <%= render partial: 'card', locals:{item: item}  %>
    <% end %>
  </div>
  </main>
    

app/views/items/show.html.erb
<main class="show-item-page container mx-auto mt-28 px-5 flex">
  <div class=" animate__animated  animate__backInLeft card flex-1">
    <img class="xl-card-rarity card-rarity" src="<%=image_path("rarity-#{@item.rarity}.png")%>">
    <div class="big-card item-card card_full max-w-sm overflow-hidden shadow-lg rarity-<%=@item.rarity%>">
      <div class="card-texture">
        <img class="w-full" src="https://i.imgur.com/vbCJQJe.png" alt="texture">
      </div>
      <div class="card-background">
        <img class="w-full " src="<%=@item.image_url%>" alt="dimaond">
      </div>
    </div>
  </div>
  <div class="show-card-content animate__animated  animate__backInRight flex-1">
    <div class=" show-title"><%= @item.title%></div>
    <div class="show-description">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad eaque, ea dicta fugit saepe minima molestias consequatur beatae, nulla, eum tempora perferendis natus pariatur aut?</div>
    <p class="text-xl mt-5 mb-2">Quantity :</p>
    <select class="rounded-3xl" name="quantity-item" id="quantity">
    <option value="">Choose a quantity</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    </select>
    <div class="card-footer show-card-footer">
    <div class="show-price "><%= @item.price %> €</div>
    <%= button_to "Add to cart", order_items_path(item_id: @item.id), class:"btn card-add-btn" %>
    </div>
  </div>
</main>