config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users
  resources :items
  resources :orders
  resources :carts
  resources :order_items, only: %i[create destroy]
  resources :orders, only: %i[create show]
  post 'order_items/:id/add' => 'order_items#add_quantity', as: 'order_items_add'
  post 'order_items/:id/reduce' => 'order_items#reduce_quantity', as: 'order_items_reduce'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :users
  end

  get '/search' => 'items#filter'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  belongs_to :user

  validates :user, uniqueness: true

  def import_order(order)
    order.order_items.each do |order_item|
      OrderItem.create!(cart: self, item: order_item.item, quantity: order_item.quantity)
    end
  end

  def self.empty_for(user)
    user.cart.destroy
    cart = Cart.new(user: user)
    cart.save
  end

  def total_price
    sum = 0
    order_items.each { |order_item| sum += order_item.total_price }
    sum
  end

  def total_quantity
    sum = 0
    order_items.each { |order_item| sum += order_item.quantity }
    sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :carts, through: :order_items
  belongs_to :category

  validates :title, presence: true,
                    uniqueness: true,
                    length: { in: 3..30 }
  # format: { with: %r{\A[\w -/]\z} }

  validates :description, presence: true,
                          length: { in: 5..500 }

  validates :price, presence: true,
                    numericality: { greater_than: 0 }

  validates :rarity, presence: true,
                     numericality: { in: 0..4 }

  validates :image_url, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  validates :status, presence: true,
                     inclusion: { in: %w[pending paid],
                                  message: '%<value>s is not a valid status' }

  def total_price
    sum = 0
    order_items.each { |order_item| sum += order_item.total_price }
    sum
  end

  def total_quantity
    sum = 0
    order_items.each { |order_item| sum += order_item.quantity }
    sum
  end

  def validate_payment
    self.status = 'paid'
    save
    puts 'methode validate_payment TESTTTTT'
    UserMailer.order_recap_to_admin(self).deliver_now
    UserMailer.send_order(self).deliver_now
  end

  def import_cart(cart)
    cart.order_items.each do |order_item|
      OrderItem.create!(order: self, item: order_item.item, quantity: order_item.quantity)
    end
  end

  def self.create_for(_user)
    order = Order.new(user: _user, status: 'pending')
    order.save
    order
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :cart, optional: true
  belongs_to :item

  # validates :item_id, uniqueness: { scope: :order_id, message: "ne peut être qu'une seule fois dans une commande" }
  # validates :item_id, uniqueness: { scope: :cart_id, message: "ne peut être qu'une seule fois dans une commande" }
  validates :quantity, numericality: { in: 1..99 }
  validate :attached_cart_or_order

  def total_price
    quantity * item.price
  end

  private

  def attached_cart_or_order
    return unless cart.nil? && order.nil?

    errors.add(:cart_id, 'has to be present if order_id is not present')
    errors.add(:order_id, 'has to be present if cart_id is not present')
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send, :create_cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_one :cart
  validates :name, format: { with: /[\w -']*/, message: 'Seules les lettres et les espaces sont autorisées' }
  # length: { in: 6..30, message: 'Le nom doit faire entre 6 et 30 caractères' }

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def after_database_authentication
    Cart.create(user: self) if cart.nil?
  end

  def create_cart
    Cart.create(user: self)
  end

  def self.admins
    User.where(admin: true).to_a
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, :my_cart?

  def show
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    @cart = Cart.new
    @cart.user = current_user
    @cart.save
    redirect_to cart_path(@cart)
  end

  private

  def my_cart?
    return if current_user.cart == Cart.find(params[:id])

    redirect_back fallback_location: root_path
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  # before_action :success, only: [:create]

  def create
    @total = params[:total].to_d
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total * 100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout'
            }
          },
          quantity: 1
        }
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    create_order
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    current_user.orders.last.validate_payment
    Cart.empty_for(current_user)
  end

  def cancel
    cancel_order
  end

  private

  def create_order
    @order = Order.create_for(current_user)
    @order.import_cart(current_user.cart)
  end

  def cancel_order
    current_user.orders.last.destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show 
    @item = Item.find(params[:id])
  end
  def filter
    @items = Item.all
    @items_filtered = Item.where(rarity: params[:search])
    @items_filtered_by_title = Item.where(title: params[:search])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders
  end
  def create
    @cart = current_user.cart
    @order = Order.new(user: current_user, status: "pending")
    @order.save
    @cart.order_items.each do |order_item|
      OrderItem.create!(order: @order, item: order_item.item, quantity: order_item.quantity)
    end
    @cart.destroy
    @cart = Cart.new(user: current_user)
    @cart.save
    redirect_to checkout_create_path(total: 50)
  end

  def show
    @order = Order.find_by(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/permission_helper.rb
module PermissionHelper
  
  def isAdmin?
    user_signed_in? && current_user.admin == true
  end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class=" sticky bottom-0 w-full bg-white shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 h-12">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="<%= root_path %>" class="hover:underline">Meowth™</a>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <a href="<%= about_path %>" class="mr-4 hover:underline md:mr-6 text-gray-500 dark:text-gray-400">A propos</a>
        </li>
        <li>
            <a href="<%= contact_path %>" class="mr-4 hover:underline md:mr-6 text-gray-500 dark:text-gray-400">Contact</a>
        </li>
        <li>
            <a href="#" class="hover:underline text-gray-500 dark:text-gray-400">Privacy Policy</a>
        </li>
    </ul>
</footer>

app/views/layouts/_hero-banner.html.erb
    <div class="banner-wrapper ">
    <div class="banner">
      <img src="https://i.imgur.com/MKLliig.jpg" alt="" class="layers " id="background" />
      <img src="https://i.imgur.com/whwRMNm.png" alt="" class="layers " id="coin-1" />
      <img src="https://i.imgur.com/9MqG1lW.png" alt="" class="layers " id="coin-2" />
      <img src="https://i.imgur.com/IY9kOyW.png" alt="" class="layers animate__animated animate__rubberBand " id="'logo-layer" />
    </div>
</div>

app/views/layouts/_hero-little.html.erb
<img src="https://i.imgur.com/KtAHcfK.jpg" alt="">

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-900 fixed-top z-1">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="burger absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center rounded-xl p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-between">
        <div class="flex flex-shrink-0 items-center">
          <a href="<%= root_path %>"><img class="block h-11 w-auto lg:hidden" src="https://i.imgur.com/V1BdlOx.png" alt="Logo "></a>
          <a href="<%= root_path %>"><img class="hidden h-11 w-auto lg:block" src="https://i.imgur.com/V1BdlOx.png" alt="Logo"></a>
        </div>
        <div class="flex self-center hidden sm:ml-10 sm:block">
            <div class="flex space-x-4">
              <div class="relative mx-auto text-gray-600 md:block hidden">
                <%= form_with url: "/search", method: :get do |form| %>
                  <%= form.text_field :search, class:"border-2 border-none bg-white h-8 pl-5 pt-2 pr-10 rounded-3xl text-sm focus:outline-none", placeholder:"Name or Rarity (0 to 4)" %>
                  <%= button_tag( :class => "button_green") do %>
                  <i class="fas fa-search"></i>
                  <% end %>
                <% end %>
                </div>
              </div>
        </div>
        <div class="flex self-center hidden sm:block">
            <div class="flex space-x-4 mr-5">
              <a href="<%= about_path %>" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-3xl px-3 py-2 text-sm font-medium">About</a>
              <a href="<%= contact_path %>" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-3xl px-3 py-2 text-sm font-medium">Contact</a>
            </div>
        </div>
      </div>
      <a href="<%= user_signed_in? ? cart_path(current_user.cart) : new_user_session_path %>" class="cart rounded-3xl"><i class="fas fa-shopping-basket fa-2x hover:bg-gray-700 rounded-3xl px-3 py-2"></i></a>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:pr-0">

        <div class="relative ml-3">
          <div>
            <button type="button" class="flex rounded-full bg-gray-800 text-sm" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <%if current_user%>
              <i class="user-connect fas fa-user fa-2x hover:bg-gray-700 rounded-3xl px-3 py-2"></i>
              <% else%>
              <i class="fas fa-user fa-2x hover:bg-gray-700 rounded-3xl px-3 py-2"></i>
              <%end%>
            </button>
          </div>
          <div class="dropp absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <!-- Active: "bg-gray-100", Not Active: "" -->
            <% if current_user%>
              <a href="<%= edit_user_registration_path%>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">My account</a>
              <a href="<%=orders_path%>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Orders</a>
              <% if isAdmin? %>
                <a href="<%= admin_users_path %>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Admin page</a>
              <% end %>
              <a href="<%= destroy_user_session_path%>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Log out</a>
            <%else %>
              <a href="<%= new_user_session_path%>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Log-in</a>
              <a href="<%= new_user_registration_path%>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Sign-up</a>
            <%end%>

          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="tuto sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pt-2 pb-3">
      <a href="<%= user_signed_in? ? cart_path(current_user.cart) : new_user_session_path %>" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" aria-current="page">Cart</a>
      <a href="<%= contact_path %>" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Contact</a>
      <a href="<%= about_path %>" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">About</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetChaton</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag image_path('favicon.png') %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://fontawesome.com/v5/icons/vial?s=solid&f=classic">
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
  <div data-turbo="false">
  <%= render "layouts/navbar"%>
  </div>
      <%= yield %>
    <div data-turbo="false">
    <%= render "layouts/footer"%>
    </div>
  </body>
</html>